Repository One-Language/Website, pull requests merged in 2021-05, with the labels that each got.

#6 Add tests
  .github/linters/.markdown-lint.yml
  .github/linters/.yaml-lint.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/super-linter.yml
  .pre-commit-config.yaml
  CNAME
  codespell.txt
  css/preloader.css
  css/style.css
  imgs/left.svg
  imgs/right.svg
  index.html
  js/main.js
  sass/style.scss
Labels: enhancement

#7 Updated footer copyright to show current year
  index.html
Labels: good first issue

#16 Fix Super Linter
  .github/workflows/super-linter.yml
Labels: bug

#18 Remove the CodeQL cpp check
  .github/workflows/codeql-analysis.yml
Labels: bug

#19 Add Dependabot
  .github/dependabot.yml
Labels: enhancement

#21 Fix misspell
  .github/workflows/lint.yml
Labels: bug

#22 Add EditorConfig
  .editorconfig
Labels: enhancement

#24 Add CODEOWNERS
  CODEOWNERS
Labels: enhancement

#25 Add Hound CI for JS
   .hound.yml
  .jshintignore
Labels: enhancement

#26 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#28 Update README.md
  README.md
Labels: documentation
