Repository One-Language/Website, pull requests merged in 2021-09, with the labels that each got.

#76 Change the style: resolve fonts problem.
  .all-contributorsrc
  .circleci/config.yml
  .editorconfig
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/dependabot.yml
  .github/linters/.markdown-lint.yml
  .github/linters/.yaml-lint.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/super-linter.yml
  .github/workflows/wrangler.yml
  .gitignore
  .hound.yml
  .pre-commit-config.yaml
  CNAME
  CODEOWNERS
  LICENSE
  README.md
  assets/css/styles.min.css
  codespell.txt
  index.html
Labels: bug

#77 Add Workers (#55)
  .eslintignore
  .github/workflows/wrangler.yml
  .gitignore
  .pre-commit-config.yaml
  lerna.json
  lrp
  package-lock.json
  package.json
  packages/anderson/.keep
  packages/baris/.keep
  packages/bryan/.keep
  packages/clay/.keep
  packages/idais/.keep
  packages/john/index.js
  packages/john/package-lock.json
  packages/john/package.json
  packages/john/wd
  packages/john/wp
  packages/john/wrangler.toml
  packages/majalian/.keep
  packages/marie/.keep
  packages/max/index.js
  packages/max/package-lock.json
  packages/max/package.json
  packages/max/wrangler.toml
  packages/roel/.keep
  packages/stevan/.keep
  packages/umut/index.js
  packages/umut/package-lock.json
  packages/umut/package.json
  packages/umut/wrangler.toml
  packages/victor/.keep
Labels: enhancement

#78 Update JS packages
  package-lock.json
Labels: dependencies
