Repository One-Language/Website, pull requests merged in 2022-11, with the labels that each got.

#142 Updated contrib.rocks link with repo queryParam
  README.md
Labels: documentation

#145 Delete .all-contributorsrc
  .all-contributorsrc
Labels: documentation

#143 Added Prettier to pre-commit
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/dependabot.yml
  .github/linters/.yaml-lint.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/super-linter.yml
  .hound.yml
  .jshintrc
  .pre-commit-config.yaml
  .prettierrc
  README.md
  assets/css/styles.min.css
  assets/js/index.min.js
  index.html
  lerna.json
  packages/john/index.js
  packages/max/index.js
Labels: code style, tests

#146 Remove CircleCI
  .circleci/config.yml
Labels: tests
