Repository One-Language/Website, pull requests merged in 2022-10, with the labels that each got.

#121 Update index.html
  index.html
Labels: documentation

#127 Makefile: add update target
  .pre-commit-config.yaml
  Makefile
Labels: tests

#128 gha: fix deploy workflow
  .github/workflows/deploy.yml
  .github/workflows/wrangler.yml
Labels: bug

#131 Fix case of GitHub
  index.html
Labels: good first issue

#134 #133: update readme screenshot
  README.md
  ui-screenshots/screenshot.jpg
  ui-screenshots/screenshot1.png
  ui-screenshots/screenshot2.png
Labels: documentation, hacktoberfest-accepted

#140 Remove all-contributors section
  .github/linters/.markdown-lint.yml
  README.md
Labels: documentation
