Repository One-Language/Website, pull requests merged in 2023-10, with the labels that each got.

#205 pre-commit autoupdate, fix spelling, format CSS
  .pre-commit-config.yaml
  assets/css/styles.min.css
Labels: good first issue, code style, tests

#202 Feat: Added the links to documentation in the navbar and Documentatio…
  index.html
Labels: good first issue

#206 Run pre-commit
  index.html
Labels: code style, tests
